SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM `admins`;
DELETE FROM `admin_password_resets`;
DELETE FROM `class_schedules`;
DELETE FROM `curriculum`;
DELETE FROM `curriculum_versions`;
DELETE FROM `educational_background`;
DELETE FROM `enrollments`;
DELETE FROM `enrollment_documents`;
DELETE FROM `enrollment_payments`;
DELETE FROM `entrance_exam_results`;
DELETE FROM `grades`;
DELETE FROM `grading_periods`;
DELETE FROM `lms_classes`;
DELETE FROM `lms_materials`;
DELETE FROM `lms_notifications`;
DELETE FROM `professors`;
DELETE FROM `professor_password_resets`;
DELETE FROM `quizzes`;
DELETE FROM `quiz_attempts`;
DELETE FROM `quiz_attempt_answers`;
DELETE FROM `quiz_questions`;
DELETE FROM `rooms`;
DELETE FROM `school_years`;
DELETE FROM `sections`;
DELETE FROM `strands`;
DELETE FROM `students`;
DELETE FROM `student_family_members`;
DELETE FROM `subjects`;

ALTER TABLE `admins` AUTO_INCREMENT = 1;
ALTER TABLE `admin_password_resets` AUTO_INCREMENT = 1;
ALTER TABLE `class_schedules` AUTO_INCREMENT = 1;
ALTER TABLE `curriculum` AUTO_INCREMENT = 1;
ALTER TABLE `curriculum_versions` AUTO_INCREMENT = 1;
ALTER TABLE `educational_background` AUTO_INCREMENT = 1;
ALTER TABLE `enrollments` AUTO_INCREMENT = 1;
ALTER TABLE `enrollment_documents` AUTO_INCREMENT = 1;
ALTER TABLE `enrollment_payments` AUTO_INCREMENT = 1;
ALTER TABLE `entrance_exam_results` AUTO_INCREMENT = 1;
ALTER TABLE `grades` AUTO_INCREMENT = 1;
ALTER TABLE `grading_periods` AUTO_INCREMENT = 1;
ALTER TABLE `lms_classes` AUTO_INCREMENT = 1;
ALTER TABLE `lms_materials` AUTO_INCREMENT = 1;
ALTER TABLE `lms_notifications` AUTO_INCREMENT = 1;
ALTER TABLE `professors` AUTO_INCREMENT = 1;
ALTER TABLE `professor_password_resets` AUTO_INCREMENT = 1;
ALTER TABLE `quizzes` AUTO_INCREMENT = 1;
ALTER TABLE `quiz_attempts` AUTO_INCREMENT = 1;
ALTER TABLE `quiz_attempt_answers` AUTO_INCREMENT = 1;
ALTER TABLE `quiz_questions` AUTO_INCREMENT = 1;
ALTER TABLE `rooms` AUTO_INCREMENT = 1;
ALTER TABLE `school_years` AUTO_INCREMENT = 1;
ALTER TABLE `sections` AUTO_INCREMENT = 1;
ALTER TABLE `strands` AUTO_INCREMENT = 1;
ALTER TABLE `students` AUTO_INCREMENT = 1;
ALTER TABLE `student_family_members` AUTO_INCREMENT = 1;
ALTER TABLE `subjects` AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;